# Generated by Django 5.2.4 on 2025-08-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_passwordresettoken_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_locked_until",
        ),
        migrations.RemoveField(
            model_name="user",
            name="failed_login_attempts",
        ),
    ]
