# Generated by Django 5.2.4 on 2025-08-27 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.TextField()),
                (
                    "media",
                    models.FileField(blank=True, null=True, upload_to="news_media/"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("is_foreign", models.BooleanField(default=False)),
                ("is_top_story", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "SubCategories",
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="ads/")),
                ("link", models.URLField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("sidebar", "Sidebar"),
                            ("footer", "Footer"),
                            ("in_content", "In Content"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "ordering": ("-id", "id"),
                "abstract": False,
            },
        ),
    ]
