# Generated by Django 5.2.6 on 2025-09-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
    ]
