# Generated by Django 5.2.6 on 2025-09-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_news_excerpt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-created"], "verbose_name_plural": "News"},
        ),
    ]
