# Generated by Django 5.2.6 on 2025-11-12 06:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_news_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="media",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="media"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
