# Generated by Django 5.2.6 on 2025-11-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_advertisement_image_alter_news_media_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="author",
        ),
    ]
