# Generated by Django 5.2.4 on 2025-08-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="adminuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
