# Generated by Django 5.2.4 on 2025-09-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_roles", "0002_adminuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adbanner",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_roles.adminuser",
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_roles.adminuser",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="admin_roles.adminuser",
                verbose_name="Author",
            ),
        ),
    ]
